import maya.cmds as cmds


transform_attrs = ['translateX',
                   'translateY',
                   'translateZ',
                   'rotateX',
                   'rotateY',
                   'rotateZ',
                   'scaleX',
                   'scaleY',
                   'scaleZ',
                   'visibility']

channel_control_attrs = ['blackBox',
                         'caching',
                         'displayHandle',
                         'displayLocalAxis',
                         'displayRotatePivot',
                         'displayScalePivot',
                         'frozen',
                         'ghostColorPostA',
                         'ghostColorPostB',
                         'ghostColorPostG',
                         'ghostColorPostR',
                         'ghostColorPreA',
                         'ghostColorPreB',
                         'ghostColorPreG',
                         'ghostColorPreR',
                         'ghostPostSteps',
                         'ghostPreSteps',
                         'ghostRangeEnd',
                         'ghostRangeStart',
                         'ghostStepSize',
                         'ghosting',
                         'ghostingControl',
                         'hiddenInOutliner',
                         'hideOnPlayback',
                         'identification',
                         'inheritsTransform',
                         'intermediateObject',
                         'layerOverrideColor',
                         'layerRenderable',
                         'lodVisibility',
                         'maxRotXLimit',
                         'maxRotXLimitEnable',
                         'maxRotYLimit',
                         'maxRotYLimitEnable',
                         'maxRotZLimit',
                         'maxRotZLimitEnable',
                         'maxScaleXLimit',
                         'maxScaleXLimitEnable',
                         'maxScaleYLimit',
                         'maxScaleYLimitEnable',
                         'maxScaleZLimit',
                         'maxScaleZLimitEnable',
                         'maxTransXLimit',
                         'maxTransXLimitEnable',
                         'maxTransYLimit',
                         'maxTransYLimitEnable',
                         'maxTransZLimit',
                         'maxTransZLimitEnable',
                         'minRotXLimit',
                         'minRotXLimitEnable',
                         'minRotYLimit',
                         'minRotYLimitEnable',
                         'minRotZLimit',
                         'minRotZLimitEnable',
                         'minScaleXLimit',
                         'minScaleXLimitEnable',
                         'minScaleYLimit',
                         'minScaleYLimitEnable',
                         'minScaleZLimit',
                         'minScaleZLimitEnable',
                         'minTransXLimit',
                         'minTransXLimitEnable',
                         'minTransYLimit',
                         'minTransYLimitEnable',
                         'minTransZLimit',
                         'minTransZLimitEnable',
                         'nodeState',
                         'objectColor',
                         'objectColorB',
                         'objectColorG',
                         'objectColorR',
                         'outlinerColorB',
                         'outlinerColorG',
                         'outlinerColorR',
                         'overrideColor',
                         'overrideColorB',
                         'overrideColorG',
                         'overrideColorR',
                         'overrideDisplayType',
                         'overrideEnabled',
                         'overrideLevelOfDetail',
                         'overridePlayback',
                         'overrideRGBColors',
                         'overrideShading',
                         'overrideTexturing',
                         'overrideVisibility',
                         'rotateAxisX',
                         'rotateAxisY',
                         'rotateAxisZ',
                         'rotateOrder',
                         'rotatePivotTranslateX',
                         'rotatePivotTranslateY',
                         'rotatePivotTranslateZ',
                         'rotatePivotX',
                         'rotatePivotY',
                         'rotatePivotZ',
                         'rotateQuaternionW',
                         'rotateQuaternionX',
                         'rotateQuaternionY',
                         'rotateQuaternionZ',
                         'scalePivotTranslateX',
                         'scalePivotTranslateY',
                         'scalePivotTranslateZ',
                         'scalePivotX',
                         'scalePivotY',
                         'scalePivotZ',
                         'selectHandleX',
                         'selectHandleY',
                         'selectHandleZ',
                         'selectionChildHighlighting',
                         'shearXY',
                         'shearXZ',
                         'shearYZ',
                         'showManipDefault',
                         'template',
                         'templateVersion',
                         'uiTreatment',
                         'useObjectColor',
                         'useOutlinerColor',
                         'viewMode',
                         'wireColorB',
                         'wireColorG',
                         'wireColorR']

list_not_channel_control_attrs = ["message",
                                  "isHistoricallyInteresting",
                                  "binMembership",
                                  "hyperLayout",
                                  "isCollapsed",
                                  "borderConnections",
                                  "isHierarchicalConnection",
                                  "publishedNodeInfo",
                                  "publishedNodeInfo.publishedNode",
                                  "publishedNodeInfo.isHierarchicalNode",
                                  "publishedNodeInfo.publishedNodeType",
                                  "rmbCommand",
                                  "templateName",
                                  "templatePath",
                                  "viewName",
                                  "iconName",
                                  "customTreatment",
                                  "creator",
                                  "creationDate",
                                  "containerType",
                                  "boundingBox",
                                  "boundingBoxMin",
                                  "boundingBoxMinX",
                                  "boundingBoxMinY",
                                  "boundingBoxMinZ",
                                  "boundingBoxMax",
                                  "boundingBoxMaxX",
                                  "boundingBoxMaxY",
                                  "boundingBoxMaxZ",
                                  "boundingBoxSize",
                                  "boundingBoxSizeX",
                                  "boundingBoxSizeY",
                                  "boundingBoxSizeZ",
                                  "center",
                                  "boundingBoxCenterX",
                                  "boundingBoxCenterY",
                                  "boundingBoxCenterZ",
                                  "matrix",
                                  "inverseMatrix",
                                  "worldMatrix",
                                  "worldInverseMatrix",
                                  "parentMatrix",
                                  "parentInverseMatrix",
                                  "instObjGroups",
                                  "instObjGroups.objectGroups",
                                  "instObjGroups.objectGroups.objectGrpCompList",
                                  "instObjGroups.objectGroups.objectGroupId",
                                  "instObjGroups.objectGroups.objectGrpColor",
                                  "objectColorRGB",
                                  "wireColorRGB",
                                  "drawOverride",
                                  "overrideColorRGB",
                                  "renderInfo",
                                  "renderLayerInfo",
                                  "renderLayerInfo.renderLayerId",
                                  "renderLayerInfo.renderLayerRenderable",
                                  "renderLayerInfo.renderLayerColor",
                                  "ghostCustomSteps",
                                  "ghostFrames",
                                  "ghostColorPre",
                                  "ghostColorPost",
                                  "ghostDriver",
                                  "outlinerColor",
                                  "translate",
                                  "rotate",
                                  "scale",
                                  "shear",
                                  "rotatePivot",
                                  "rotatePivotTranslate",
                                  "scalePivot",
                                  "scalePivotTranslate",
                                  "rotateAxis",
                                  "transMinusRotatePivot",
                                  "transMinusRotatePivotX",
                                  "transMinusRotatePivotY",
                                  "transMinusRotatePivotZ",
                                  "minTransLimit",
                                  "maxTransLimit",
                                  "minTransLimitEnable",
                                  "maxTransLimitEnable",
                                  "minRotLimit",
                                  "maxRotLimit",
                                  "minRotLimitEnable",
                                  "maxRotLimitEnable",
                                  "minScaleLimit",
                                  "maxScaleLimit",
                                  "minScaleLimitEnable",
                                  "maxScaleLimitEnable",
                                  "geometry",
                                  "xformMatrix",
                                  "selectHandle",
                                  "dynamics",
                                  "specifiedManipLocation",
                                  "rotateQuaternion",
                                  "rotationInterpolation", ]


def unlock_channels(custom=True):
    sel = cmds.ls(sl=True)

    if sel:
        for each in sel:
            # unlock custom channels mode
            if custom:
                attrs = cmds.listAttr(each)
                # Filter the attributes that are not related with channel control attributes
                attrs = [a for a in attrs if a not in list_not_channel_control_attrs]

                # Filter the channel control attributes
                # We will get the basic transform attributes,
                # And also user custom attributes
                attrs = [a for a in attrs if a not in channel_control_attrs]

            # classic unlock channels mode (['translateX', 'translateY', 'translateZ', 'rotateX', 'rotateY', 'rotateZ', 'scaleX', 'scaleY', 'scaleZ', 'visibility'])
            #
            else:
                attrs = transform_attrs

            if attrs:
                # Unlock and unhide the attributes
                for attr in attrs:
                    cmds.setAttr(each + "." + attr, lock=False, keyable=True)

    else:
        # If nothing selected
        cmds.warning("Please select the targets .")


unlock_channels()